# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SynFlood < Formula
  desc "syn-flood starts a syn flood attack with raw sockets. created for learning low level network ops"
  homepage "https://github.com/joshsagredo/syn-flood"
  version "2.0.0"
  license "apache-2.0"

  on_macos do
    url "https://github.com/joshsagredo/syn-flood/releases/download/v2.0.0/syn-flood_2.0.0_darwin_x86_64.tar.gz"
    sha256 "16a9d6a1bb9103438f8d964ade699bade86d6ca3407b333cc5f09776d3480a4b"

    def install
      bin.install "syn-flood"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SynFlood
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joshsagredo/syn-flood/releases/download/v2.0.0/syn-flood_2.0.0_linux_x86_64.tar.gz"
      sha256 "4dc5cf3bc4f576db7ea57758c15a332a806d54760c65791e465f15458fb8371f"

      def install
        bin.install "syn-flood"
      end
    end
  end
end
